name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_maps: ^6.0.0
  js: ^0.6.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.0
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  footer: ^0.0.4
  http: ^1.0.0
  fl_chart: ^0.65.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/Images/traffic-jam.jpg
    - assets/map_with_markers.html
    - assets/Images/hourglass.png
    - assets/Images/hourglass2.png

