name: map_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  geolocator: ^11.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.1
  intl: ^0.18.1
  google_maps_flutter: ^2.12.1
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.6
  google_maps_flutter_web: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map_img.png
    - assets/traffic-jam.jpg
    - assets/logo.jpeg
