// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnVBfFW4N3N5NEERVxhhmvVGzszHTdjs',
    appId: '1:951216708050:web:41b467001bf00d39ab100b',
    messagingSenderId: '951216708050',
    projectId: 'projectcapstone-cd867',
    authDomain: 'projectcapstone-cd867.firebaseapp.com',
    storageBucket: 'projectcapstone-cd867.firebasestorage.app',
    measurementId: 'G-62EDGR29H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-AWdm-aKnAhFDz-AOsY2Rqa7PZV1jIwo',
    appId: '1:951216708050:android:d618d46bf2546a26ab100b',
    messagingSenderId: '951216708050',
    projectId: 'projectcapstone-cd867',
    storageBucket: 'projectcapstone-cd867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtDBvMNWnFT13DHGL4p5cAykWYvKPwBY',
    appId: '1:951216708050:ios:27a9e0d4a61bd0f4ab100b',
    messagingSenderId: '951216708050',
    projectId: 'projectcapstone-cd867',
    storageBucket: 'projectcapstone-cd867.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtDBvMNWnFT13DHGL4p5cAykWYvKPwBY',
    appId: '1:951216708050:ios:27a9e0d4a61bd0f4ab100b',
    messagingSenderId: '951216708050',
    projectId: 'projectcapstone-cd867',
    storageBucket: 'projectcapstone-cd867.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEnVBfFW4N3N5NEERVxhhmvVGzszHTdjs',
    appId: '1:951216708050:web:3f914699e93ecfa5ab100b',
    messagingSenderId: '951216708050',
    projectId: 'projectcapstone-cd867',
    authDomain: 'projectcapstone-cd867.firebaseapp.com',
    storageBucket: 'projectcapstone-cd867.firebasestorage.app',
    measurementId: 'G-Z523Z1ZSVV',
  );
}
